### ISSUE TITLE
Initial to-do list from an initial UI review

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/eea-attendee-importer#16]
### General

- [x] Attendee Importer Usage tab needs content. 
Currently has information about a shortcode which I'll assume is from boilerplate. A simple overview of the steps would be helpful here - see https://github.com/eventespresso/eea-attendee-importer/issues/21

### Step 1
If possible, can the upload input not be the image uploader? It's confusing to see "Click to add an image" and when you click the button, it opens the media library. Maybe use wp_upload_bits() here?

### Step 2
- [x] This step could use a box or section with a list of minimum required fields. For example the list could have:
- First Name
- Last Name
- Email
- Reg status
- Transaction status
- and whatever other fields must be completed
Bonus: The box could show feedback when one of the required fields is mapped.
![screen shot 2019-02-01 at 10 28 23 am](https://user-images.githubusercontent.com/891156/52132231-b2a2fd80-260c-11e9-8ee1-55c0ad9030e5.png)

- [x] Needs validation to enforce required fields. Currently if some fields are missing you get an exception on step 5

### Step 3

- [x] The input needs more width (see https://github.com/eventespresso/event-espresso-core/pull/1029)
![screen shot 2019-02-01 at 10 33 07 am](https://user-images.githubusercontent.com/891156/52132345-f1d14e80-260c-11e9-8cf4-88109ae90e69.png)
- [x] The events should be in desc. order, so the most recently added events need to appear first

### Step 4
- [x] The input needs more width

### Step 5
I'm not sure what's going on here. There's an input that's labeled Input1 and if I type something into that input, it redirects to the Event Espresso > Registrations list table. 
- [x] Add a message that says the job is complete and include a link to the associated event's registration list. The link text should say "Go to the registration list for this event" or something similar.

**Comment by mnelson4** [comment]
Great feedback thanks. Ya you're on the right track there.

Yeah the usage tab was from boilerplate code.

Yeah having a regular file input and using `wp_upload_bits` would probably be better. MVP probably.

Having the box showing the minimum fields would be good UX, but IMO might be a best after the MVP. Doing server-side validation will be much easier IMO (and we probably want that regardless). Would you like this as part of the MVP?

And ya, step 5 hasn't been implemented at all. It was going to contain a summary of data that was imported.

**Comment by mnelson4** [comment]
Oh ya, just text with a list in it is totally easy for an MVP. Using JS to update it wouldn't be too hard, but probably better for after.

And ya, validating that form server-side will be quite doable too.

**Comment by mnelson4** [comment]
So I'm going to add this to the 1.0.0 milestone to make sure all your comments get addressed before release.

**Comment by mnelson4** [comment]
> If possible, can the upload input not be the image uploader? It's confusing to see "Click to add an image" and when you click the button, it opens the media library. Maybe use wp_upload_bits() here?

FYI we can change the text to read "Click to select CSV file" or something.

If it's not a big deal I'd rather stick with that (integrates better with other plugins, like add file from server plugin, and it's easier to develop with IMO) but if you think it's important for the MVP I'll make the change to a regular file upload input

**Comment by joshfeck** [comment]
I think the Attendee importer's UI should closely follow how other WordPress importers do it. In this case, using a media importer is confusing because it's a UI that includes options to build a photo gallery and/or select from previously uploaded images.

An example of the standard way to upload an import file can be found by checking the WordPress importer under Tools > Import. Here's a screenshot:
![screen shot 2019-02-12 at 10 11 31 am](https://user-images.githubusercontent.com/891156/52645373-a6415f00-2eae-11e9-9ad0-165614bb908f.png)

If you feel this design aspect needs further discussion maybe you could start a p2?

**Comment by mnelson4** [comment]
Ya that's fine, I just wasn't sure if your only objection was the wording. I think the media uploader might be customizable to remove all that extra stuff, but that would probably be more work than using a normal file upload field. (I'm just wanting to get something releasable as quick as possible.)

I'll switch it to the file upload field. Thanks for the feedback.

**Comment by mnelson4** [comment]
ok I think we've either resolved these issues, or created separate tickets for them. So I think this can be closed, right @joshfeck
